[versions]
#plugins
shadow-plugin = "9.1.0"
#kotlin
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
#minecraft
paper = "1.21.10-R0.1-SNAPSHOT"
packetevents = "2.11.1"
nbtapi = "2.15.5"
skinsrestorer = "15.9.1"

[libraries]
#kotlinx
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
#minecraft
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
nbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "nbtapi" }
skinsrestorer = { module = "net.skinsrestorer:skinsrestorer-api", version.ref = "skinsrestorer" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }

[bundles]
kotlinx = ["kotlinx-coroutines", "kotlinx-serialization"]


