[versions]
#plugins
shadow-plugin = "9.1.0"
#kotlin
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinx-atomicfu = "0.30.0-beta"
kotlinx-immutable-collections = "0.4.0"
#orm
exposed = "1.0.0-rc-4"
mysql = "1.4.1"
postgres = "1.1.1.RELEASE"
#minecraft
paper = "1.21.10-R0.1-SNAPSHOT"
packetevents = "2.11.1"
nbtapi = "2.15.5"
skinsrestorer = "15.9.1"

[libraries]
#kotlinx
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-atmoicfu = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "kotlinx-atomicfu" }
kotlinx-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable-collections" }
#orm
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt", version.ref = "exposed" }
mysql = { module = "io.asyncer:r2dbc-mysql", version.ref = "mysql" }
postgres = { module = "org.postgresql:r2dbc-postgresql", version.ref = "postgres" }
#minecraft
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
nbtapi = { module = "de.tr7zw:item-nbt-api", version.ref = "nbtapi" }
skinsrestorer = { module = "net.skinsrestorer:skinsrestorer-api", version.ref = "skinsrestorer" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-atmoicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "kotlinx-atomicfu" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin" }

[bundles]
kotlinx = ["kotlinx-coroutines", "kotlinx-serialization", "kotlinx-atmoicfu", "kotlinx-immutable-collections"]
orm = ["exposed-core", "exposed-r2dbc", "exposed-json", "exposed-crypt", "mysql", "postgres"]


